[package]
name = "emu-6502"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "emu-6502"
path = "src/bin/cli.rs"

[[bin]]
name = "emu-6502-gui"
path = "src/bin/gui.rs"

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
eframe = "0.23.0"
egui_extras = "0.23.0"
rfd = "0.12.0"
